CFLAGS = -Wall -Wextra -Werror

SOURCES = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_strlen.c ft_toupper.c ft_tolower.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_strjoin.c ft_strncmp.c ft_atoi.c ft_split.c ft_strchr.c ft_strrchr.c ft_substr.c ft_strmapi.c main.c

all:
	cc ${CFLAGS} ${SOURCES}

clean:
	rm -f a.out

fclean: clean
	rm -f ${NAME}

re: fclean all
